#테스트할때..
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_test;MODE=MySQL # 메모리모드 (mem) : 휘발성 테스트, h2 DB가 생성되지 않고 메모리에 담김, 서버 종료 시 DB가 사라짐
    username: sa
    password: